### ISSUE TITLE
New Deneb version is in AppSource, but Power BI is still showing the old version

### ISSUE THREAD

**Issue by AlpsBI** [avatorl/Deneb-Vega-Help#11]
Hi Andrzej,
I have seen the release of Deneb 1.7 and I also updated the visual in Power BI, although I can't use the new features, they are still missing. I posted you the editor. The new dark mode button for example ist not showing. Am I missing something? 
Thanks for your help
Lukas
![grafik](https://github.com/user-attachments/assets/2e217090-7e8a-4c67-aeb4-c4070b2a3361)

**Comment by avatorl** [comment]
Hi Lukas,

It's temporary still being 1.6.2.1 despite saying 1.7 in the AppSource.
See  https://github.com/deneb-viz/deneb/issues/392 for more details.

**Comment by AlpsBI** [comment]
Ok. Thanks. So I have only to wait a few more days/weeks?

**Comment by avatorl** [comment]
Right, just wait. Or use the suggested alternatives if you want to try 1.7 right away.
