### ISSUE TITLE
[Vega] Treemap with Categories and Subcategories - Column-headers

### ISSUE THREAD

**Issue by maxanatsko** [avatorl/Deneb-Vega-Help#12]
Hello,
I'm attempting to reproduce well-known stock market overview infographics in Vega/PowerBI.
![image](https://github.com/user-attachments/assets/7a56430b-274c-4c3e-9750-e16bb6d88edf)

So far I was able to get to this state.
![image](https://github.com/user-attachments/assets/e9750117-4c31-4a9e-8edd-8d542929f630)

However, I'm struggling with groups and roles (eg. column-header) etc, to be able to display category and subcategory aligned with the rectangles within treemap.
[Gist with the JSON spec](https://vega.github.io/editor/#/gist/22a3017e787828a134e932e26541c74f/spec.json).
*I was not able to make it work within Github editor, but in PBI it works.

Thank you in advance for your help.

References used:
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhBIGmNhBoAvOGhA4kAE2kbtWmuLJoBM+DTJY0ARgAMtmQHcaW+jYEOQSsuKQAbCDQAbVBfBDV0eG04ACcACTgLKxlifwYIgGZbAF8pUKRw9Uw6PzgEpMxdVL90tAAmHIBdGWQYgGtA1BCQTABPHAiQMhi2BhxdEdL1KDYahHEAWmLMKZk4cRmtCNAxrSRMbZAAMxo-PzRQatr0GLgdXIxEy0rUUG9fc-Rl0vLnkAfnK4YBcvBYPupAW5stCWkh2p1un0BkU4AAPSprDZsLYg3b7Q6okEnOB+HSvIYjMYQlxQloMPwvWyUAQPXpEmgksmgYajcaRJ5WB4IemM5kPfxgkFXQZQdYHGL-GRMJAQEmGQ7S9QIFxaKYPA7oqVpQZ+JC9UaYAAE3zUDyOEkwAGUVBrjTY6naHQB1AUvS5u9BMWb3aHZRq5UBIwY8qkySYy2YMeYLKJbBWYzaHPEHdlnI01aO3daKx4VEHvfzqVOxX6CmRsTRQOhs8ma1BMj1OGnA8kVz4gSEwS0ES11f4wkCtDrBSP9QYGjEgdaZ3E4PY58mE8nE0kgmN8gfdkvChloJksmQt0A7rkU3lV33HkVnsUyCU+fPXECy8TykvK1U-HVT9Bm1LRdVtGQFxAh9ohiawS3tX9nVUGDUAADlDMMIx6Od1H3XRl2xQ45ViEFB3LMFK3QQdh1HEtzD+XsqP7Ri62OU5Pn9At1CA54mB40NYXhGdcORL40UXIicXJUiFXJaDWwDHpJIQh4ALVcRXR4r4G3HaFwzyMTC3vONZgTOZFmrdMlyxGSdjXfFcy4kA2xAATageBskCbPo0PPB42L9UEfGox44NrSoASPZjQv7WiRzHITJzhaculncSVMNDNiNXdcCXZTk90pA8KKFZ921fEArw4oryQI-ky3K09KovWQ+MkJSdO-OT-xVTTtK-MCIJLRTuK-aykpkJCnRdNDMNDQyMpM2NbJXWTfzI8kKNi8EaO7OiptLJi3hYh8mumzi0JAPisGGOBi2SqcEWWlFsrW3KNr-BTJOuhcjo0oCtL+vSsPDZobrNC0QXfTr2vOGQf2+zAYnSKCSjgAAhJBxDJTxrOx3GzxkTRwMMYx23rI4jlVYKZksgAVDHKLiooMcikt6aTcQEjglm9vCtMOeSm0QUUoZ1lifxrWZ6EgA)
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhBIGmNhBoAvOGhA4kAE2kbtWmuLJoBM+DTJY0ARgAMtmQHcaW+jYEOQyAE4BrCGgA2qCYAJ44auhk3mwMOLoxADaRIFBsiQwI4gC0mHTJunmYBaghcAAemOqJSKGxmAAERQUyTEgQcImGkaDESBkpCvEAvsMycOJpWj0gcVpImDMAZjSJiWi9-Qwp3nA6YxhwFlalIH0DaABMtgfOrjAbIEpk4v3qd26jo1Ih4SnRsXiMiSKTSGSy2Xg2jg3kK+Rmi0q6ih0281l0SwkmAAyipIgAOGT9CySdDJJZVA4TKYzOYLZardanc7bdTROATEAHcyWKrMraRADMNxkbE0UDooUeLMitkol1uLjcp2eryZIA+MAIly5Xx+IDCETZMTiumpbGmjwmi1hp01j1Vb3Qmu1XLMR15DpJTsOx0pMggmBivhmMvUTAueq8SD8AVQwQNf3UiKq40mFpm1phjxT0oFyYq-pAbQ6XXEofz6CGutGAF0xr8jVETUCQCD1GDMjkUdmZM0EYXkXBod4dTJMeIcXi0ITZF0XtU4BS3SBzZbTnTFo8Vms8xd0BHWQcxUgJWE96zUHKBNyPSdNvvhYr7l6Xj6XTqDoHgxX98XI3qjb-C2ZrpuuoBZraoD2iq3rqh+K48veTxwUOfort+bAhhewEcpIUY+P4QRAQWSJpjSVqTtmpy5vyf65gcJadN0OHJmKNbDPWtYyDUdTyI8xILug-TrDIUCQWgQbbH28IAEJIOIOhXu6I7yYpaAiga8I5oOUQTDC-RNNpoxAA)
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQXEACOAA8kCHABs4OtgDMdmRXERIcOk0gCebBph2W2inTBo4RSRFWBooJBMdWSRMKmkQAHcaWXo0AE4ANgAGGXgaMiw0AWzckBwkWVkacTI0ACZKARkkTzYIGgAvODQQcQkemQ6ycUiINABtUFGEHvQXd08E4kiGOZAIAEcGEJpLVwSmGtk0UBqcJfQIODMoTAS2VXVx1AmN7d39w5qQg6GTcJwapQHoAXQAvuCpNMjOskBAcHA7gAlWLsZarOYARkomRkR3EJ1QZ3EF3u6GCtUGIAQNTQWJkyH0xSGmDgODQ2UoWMhoJkMTikxhs16tnsCQYihMvQF-EsLjsIjEkhktiQ4ggPkUCCFIEwrkRvQgarUXxkAGs4Ad0CkEhU7OJMABpK29e1wR0gKGgfWG9BihwcmSWQImIkbLrUsSKcmgEM3cMrExrL0yRQeQloWxrRlwehsImgYajaXzNwee5QkDBNRsU4RkaRXrwxEotF1qsdbq64tN9DJVIwVNFgol3r5QqViEQ6F9WG9frycZDDyhdYBhJqjVanWvH0G9YhkxsxQJAw4U-oAUMBCUMJhh1emfC9ZmJCkZcbVcg0V2albzVfF3KY9QPXojxPM99AvXoAEJr1ve9ZEfcFpyGCIzBeECZnWKA2BMXxNzA9BfGqMd+TYZA6WJORYhQdBFwUBJ4zDBd5yrSkyDmN4AGIAGYsQADnqJgThkHjMiYJAgUyBIePSJFpKxOSoEyWQmDgSw5LgTIBBKMSQB4yxZEE2Q+KgOTjOkyTLKqbIkHqOSBKQPiBAAFjkgB2NyoDczzZPEpAsVkdJ0iYFTPLgdIoGyLyBEkphlPEhT0iQKBBLkpgoFE2QLPEmIYjgcLxMyPjStKuSsiqgLDNEuqDJ4kKmvSEBnznEUrkjIi-RAUifmlCiqI0CZcgZeopD4vlq3VLjJnqeKpHqQTFtGty2pw3pHjSug-lAnq+vIuRKKQaiRqkMaJqmzjuK5LFmi5e7KGWrE0JpEJzSw-cersO5mPTXdQFlBcCyYqsahPNK1FINBLDGOAZA9PD5HrD1IJoo9SyLDDcPwwjg1DcMNshGQGBwAU5lAZl0YJ3p9FiqtrTjGn0FcemZH0RzqYTWnlIZzmme5lnechb09vWH77mDf76yB+Y4HfUGEfEJGKZAVGgnrY100teskxTdAjMsLTiZAUnyfrKmBdY9A6dTEBGZAFjw1Zu2OfrJ2ebt1x+cd5n7d5-GTExkA9fXSkERCVGvSrGA2FIS8maD3XMV6OwThF0XfXXAxJcd6WaNlvoQfGMHHSCSGaGh1BYZMa4lZVlGy4Tx2JFjEOU-QAAJG5SDUCIdAAOTgHMdE0ZQmyrSJR2T5NcPV08qyk64AXEVXQ96WkqjMO2MZn-XDNKNm9Rz92-aJ4NW4AZS6mjoEidYu2pD2r3ZNIqwxgB5CooB2zXsc27+v98aCzkK-IcJszaxFVpbBsY50APR0AAKh0AACgQpQOmOgADU0RYg3gwViAAlF7TWo4+wgAQcgtBeDbys2wbgzA+DXBEOjrycEQA)

**Comment by avatorl** [comment]
@maxanatsko , I'm sorry for the late response.

> I was not able to make it work within Github editor, but in PBI it works.

Likely because of the // comments. Not supported in Vega (not valid JSON). That's JSONC, supported in Deneb since version 1.7

Also I would check the data transformations... After removing the comments I see just zeroes in the transformed data tables:
![image](https://github.com/user-attachments/assets/fa6beb90-063a-4811-91a0-b5f09ca265c5)
