### ISSUE TITLE
Deneb and Adding New Column to the PBI-David Gantt Chart

### ISSUE THREAD

**Issue by aminihockey** [avatorl/Deneb-Vega-Help#13]
Hello,

Is there any possible way to add a couple of new Columns to the Deneb _PBI-David_ Gantt Chart so it can be displayed the same way as the Task, Start, End, Days, and Progress is shown on the left part of the chart? I have to add a new Column called "Importance" in front of the Progress column. 

_UPD by avatorl: https://github.com/avatorl/Deneb-Showcase/tree/main/Gantt%20Chart_

<img width="425" alt="Mockup" src="https://github.com/user-attachments/assets/eb1c58de-8a4b-49e8-aa45-e4c962f4361d">

I added the below code for adding an additional column to the specification, but it is NOT showing as a part of the report.
```
{
      "name": "ImportanceColumnWidth",
      "value": 55
    },
```

Any help on this will be greatly appreciate it.
Thank you,
Kamran

**Comment by avatorl** [comment]
Hi Kamran,
what you added is just a constant (Vega "signal"). It means ImportanceColumnWidth = 55, so you use ImportanceColumnWidth  later in the code instead of 55.

To add one more column, you need to copy one of the groups that were used to create the existing groups (a group creates cells of the column and contains "text" marks to display the content).

For example, find 

```
{
          "type": "group",
          "name": "daysColumnWidth",
...
}
```

copy the entire group, add the copy to the specification (after the "daysColumnWidth" group), rename the new group, then change column content (see comments in the following code):
```
       {
          "type": "group",
          "name": "ImportanceColumn", // renamed from "daysColumnWidth"
          "style": "cell",
          "title": {
            "text": "Importance", // "Importance" instead of "Days" (column title)
            "anchor": "end",
            "frame": "group",
            "align": "right"
          },
          "encode": {
            "update": {
              "width": {
                "signal": "ImportanceColumnWidth" // replaced (column width will be based on the new constant)
              },
              "stroke": {
                "value": "transparent"
              },
              "height": {
                "signal": "height"
              }
            }
          },
          "marks": [
            {
              "type": "text",
              "style": "col",
              "clip": true,
              "from": {
                "data": "yScale"
              },
              "encode": {
                "update": {
                  "align": {
                    "value": "right"
                  },
                  "x": {
                    "signal": "ImportanceColumnWidth" // replaced
                  },
                  "y": {
                    "signal": "scale('y', datum.id)+bandwidth('y')/2"
                  },
                  "text": {
                    "signal": "datum.importance" //replaced. requires importance column in the "dataset"
                  },
                  "fontWeight": {
                    "signal": "datum.phase == datum.task?'bold':'normal'"
                  },
                  "font": {
                    "signal": "datum.phase == datum.task?'Arial':'Segoe UI'"
                  },
                  "fill": {
                    "signal": "toString(datum.id) == itemHovered.id  ?merge(hsl(scale('cDark', datum.phase)), {l:0.40}):textColour"
                  }
                }
              }
            }
          ]
        },
```

also update "columnsWidth" signal (total width of all the columns (add "+ImportanceColumnWidth")

```
    {
      "name": "columnsWidth",
      "update": "startColumnWidth+taskColumnWidth+startColumnWidth+endColumnWidth+daysColumnWidth+ImportanceColumnWidth +progressColumnWidth+(columnPadding*5)"
    },
```

That should work. Maybe I missed something minor...

**Comment by aminihockey** [comment]
Thanks so much. That worked. The only thing I can't figure it out after 30 minutes reviewing the code is to insert the space between Days and Importance. 

<img width="163" alt="image" src="https://github.com/user-attachments/assets/a83bfda1-d951-404a-b124-a68021fd9b02">
I'll review the code and see if I can figure it out without taking too much of your time.
Thank you

**Comment by aminihockey** [comment]
Alright, increased the width to 65 and it did the job. thanks so much.
 {
      "name": "ImportanceColumnWidth",
      "value": 65
    },
