### ISSUE TITLE
Changing the Deneb Gantt Chart Datasource

### ISSUE THREAD

**Issue by aminihockey** [avatorl/Deneb-Vega-Help#15]
Hello,
I have two issues that if you could provide some directions, I would greatly appreciate it.
1) 
I don't seem to be able to change the data source for the Deneb Gantt Chart from the internal power bi table to my Excel file that has the project information for my organization. Is there a way to change the data source for the query is being used to populated the Gantt Chart? 
2) I added a new Custom called "Importance" and it is showing as a part of the heading, but the actual data is not getting populated. I added the column as a custom column to the Table using Transformer, but I think I need to make changes to the actual source file to bring in the Importance Column and show the values. 
<img width="354" alt="image" src="https://github.com/user-attachments/assets/4fe9ef77-bfb2-4851-aa13-76d8d74e1623">

Thanks so much for your time.
Kamran

**Comment by avatorl** [comment]
> I don't seem to be able to change the data source for the Deneb Gantt Chart from the internal power bi table to my Excel file that has the project information for my organization. Is there a way to change the data source for the query is being used to populated the Gantt Chart?

1. If you use it inside of Deneb visual installed from App store (certified version of Deneb), then the only data table you can have as an input is "dataset" that references Power BI fields/measure added into the visual.
2. If it's a standalone version (downloaded as a file), you can use "url" property of a data table to reference external CSV or JSON files (must be hosted somewhere, for example in GitHub repository).
3. If it's just Vega, outside of Deneb and Power BI, you can use "url" property as well, but you can also have more than one input tables (multiple tables with "url" property).

You can't reference an Excel file (.xlsx) from Vega code.


> I added a new Custom called "Importance" and it is showing as a part of the heading, but the actual data is not getting populated. I added the column as a custom column to the Table using Transformer, but I think I need to make changes to the actual source file to bring in the Importance Column and show the values.

I assume "importance" is not something you can calculate, you definitely need to bring it from the data source. A custom column should work as well, but that doesn't make much sense (or is importance is something you can calculate from the other column? If yes, then "formula" transform should do the job.

**Comment by aminihockey** [comment]
Sorry, I was out of town last week. Thank you for your time. I'll review your recommendations.
